[package]
name = "rgrep"
version = "0.1.0"
authors = ["gauravsaini"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
clap = "2.33.1"
failure = "0.1.8"
